services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: zapperbot
      POSTGRES_USER: zapperbot
      POSTGRES_PASSWORD: zapperbot

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
